# Generated by Django 5.2.1 on 2025-05-17 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Konfedra',
                'verbose_name_plural': 'Konfedralar',
            },
        ),
        migrations.CreateModel(
            name='TeacherUsersStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('juda_ham_qoniqaman', models.IntegerField(default=0)),
                ('ortacha_qoniqaman', models.IntegerField(default=0)),
                ('asosan_qoniqaman', models.IntegerField(default=0)),
                ('qoniqmayman', models.IntegerField(default=0)),
                ('umuman_qoniqaman', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teachertopic')),
            ],
            options={
                'verbose_name': "O'qituvchining statistikasi",
                'verbose_name_plural': "O'qituvchilarnining statistikasi",
                'ordering': ['-updated_at'],
            },
        ),
    ]
