# Generated by Django 5.2.1 on 2025-05-19 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_teacherusersstats_telegram_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachertopic',
            options={'verbose_name': 'Kafedra', 'verbose_name_plural': 'Kafedralar'},
        ),
    ]
